spring:
  application:
    name: eureka-server

server:
  port: 8081



eureka:
  client:
    service-url:
      defaultZone: http://node2:8082/eureka/,http://node3:8083/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    hostname: node1
