spring:
  application:
    name: eureka-server

server:
  port: 8083



eureka:
  client:
    service-url:
      defaultZone: http://node1:8081/eureka/,http://node2:8082/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    hostname: node3
