spring:
  application:
    name: eureka-server

server:
  port: 8082



eureka:
  client:
    service-url:
      defaultZone: http://node1:8081/eureka/,http://node3:8083/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    hostname: node2
